# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_filterprice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterprice',
            name='category',
            field=models.ManyToManyField(related_name='filterprices', to='categories.Category'),
        ),
    ]
