# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_remove_filtercheck_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercheck',
            name='category',
            field=models.ManyToManyField(related_name='filterchecks', to='categories.Category'),
        ),
    ]
