# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20160707_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='products/images', verbose_name='Fotos del producto'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción general'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, help_text='15%,30%, etc', null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_price',
            field=models.FloatField(verbose_name='Precio Bruto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_principal',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='products/images', verbose_name='Imagen principal del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=400, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio con descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.Category', verbose_name='Sub categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.CharField(choices=[('usd', 'Dólares'), ('pen', 'Nuevos Soles')], max_length=3, verbose_name='Unidad de precio'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.Characteristic', verbose_name='Especificacion'),
        ),
    ]
