# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 04:39
from __future__ import unicode_literals

import config.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160525_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_list',
            field=config.utils.fields.MListField(blank=True, default=[], null=True, verbose_name='List de productos deseados'),
        ),
    ]
