# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
