# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 4, 4, 3, 14, 315583, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
