# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171115_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name=b'Descripci\xc3\xb3n general'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.Category', verbose_name=b'Sub categor\xc3\xada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.CharField(choices=[(b'usd', b'D\xc3\xb3lares'), (b'pen', b'Nuevos Soles')], max_length=3, verbose_name=b'Unidad de precio'),
        ),
    ]
