# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_remove_filtercolor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercolor',
            name='category',
            field=models.ManyToManyField(related_name='filtercolors', to='categories.Category'),
        ),
    ]
