# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_filtercolor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optioncolor',
            name='filter_color',
        ),
        migrations.DeleteModel(
            name='OptionColor',
        ),
    ]
