# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterchecks', to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FilterColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtercolors', to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FilterPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.FloatField(max_length=200)),
                ('max_price', models.FloatField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterprices', to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OptionCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('filter_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionscheck', to='categories.FilterCheck')),
            ],
        ),
        migrations.CreateModel(
            name='OptionColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('filter_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionscolor', to='categories.FilterColor')),
            ],
        ),
    ]
