# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_product_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='Monto total')),
                ('voucher', models.FileField(blank=True, null=True, upload_to='sales/vouchers')),
                ('state', models.CharField(choices=[('requested', 'Pedido'), ('canceled', 'Cancelado'), ('paid', 'Pagado'), ('delivered', 'Entregado')], default='requested', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='products.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='sales.Sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(related_name='sale', through='sales.SaleProduct', to='products.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
