# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_code_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
