migrate:
	python manage.py migrate

fixtures:
	python manage.py crear_categories
	python manage.py crear_filtercheck
	python manage.py crear_filtercolor
	python manage.py crear_filterprices
	python manage.py crear_subcategories


all: migrate fixtures

