# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20160526_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterprice',
            name='category',
        ),
    ]
