# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160617_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_principal',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=b'products/images', verbose_name=b'Imagen principal del producto'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product', verbose_name=b'Producto'),
        ),
    ]
