# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'products/images', verbose_name=b'Fotos del producto')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name=b'Nombre')),
                ('slug', models.SlugField(blank=True, max_length=400, null=True)),
                ('model', models.CharField(max_length=400, verbose_name=b'Modelo')),
                ('description', models.TextField(blank=True, verbose_name=b'Descripci\xc3\xb3n general')),
                ('unit_price', models.CharField(choices=[(b'usd', b'D\xc3\xb3lares'), (b'pen', b'Nuevos Soles')], max_length=3, verbose_name=b'Unidad de precio')),
                ('gross_price', models.FloatField(verbose_name=b'Precio Bruto')),
                ('discount', models.PositiveIntegerField(blank=True, help_text=b'15%,30%, etc', null=True, verbose_name=b'Descuento')),
                ('net_price', models.FloatField(blank=True, null=True, verbose_name=b'Precio con descuento')),
                ('is_enabled', models.BooleanField(default=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.Category', verbose_name=b'Sub categor\xc3\xada')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_enabled', models.BooleanField(default=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.Characteristic', verbose_name=b'Especificacion')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product', verbose_name=b'Producto'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.Product', verbose_name=b'Producto'),
        ),
    ]
